# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish Package

on:
    workflow_dispatch:
    release:
        types: [created]

jobs:
    build:
        name: Build and Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              name: Checkout
            - uses: actions/setup-node@v3
              name: Pull in Node
              with:
                  node-version: 22
                  registry-url: https://registry.npmjs.org/
            - run: npm install
              name: Install Symbol Packages
            - run: npm run install:do --workspaces
              name: Install Package Deps
            - run: npm run build
              env:
                NODE_OPTIONS: --max-old-space-size=6144
              name: Build
            - run: npm publish ./dist/light --access public -q
              name: Publish Light
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
            - run: npm publish ./dist/regular --access public -q
              name: Publish Regular
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
            - run: npm publish ./dist/bold --access public -q
              name: Publish Bold
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
